name: build-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v2
      - name: Build and test
        run: docker buildx build -t odota/parser --platform linux/amd64,linux/arm64 --output type=docker .
      - name: Push to Docker
        if: github.ref == 'refs/heads/master'
        run: ./scripts/postbuild.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
